### ISSUE TITLE
Endpoint crashes when assembly is not found

### ISSUE THREAD

**Issue by adeepak12** [ParticularLabs/NServiceBus.FileBasedRouting#26]
I am attempting to use a centralized routing file as illustrated below -
```
<endpoints>
  <endpoint name="EndpointA">
    <handles>
       <commands assembly="EndpointA.Contract" />
    </handles
  </endpoint>
  <endpoint name="EndpointB">
    <handles>
       <commands assembly="EndpointB.Contract" />
    </handles
  </endpoint>
</endpoints>
```

The project that hosts EndpointA only has a reference to EndpointA.Contract. Likewise, EndpointB only has a reference to EndpointB.Contract. When starting either endpoint, the application crashes, since it is trying to load all the assemblies included in the routing file. IMO, I don't think it is reasonable to expect all endpoints to reference all message contracts. Of course, GAC is an option, but I would prefer not to, if it can be avoided.

**Comment by SzymonPobiega** [comment]
Hi @adeepak12 

Do you use the latest version? This problem has been [fixed in 1.2](https://github.com/ParticularLabs/NServiceBus.FileBasedRouting/issues/21).

**Comment by adeepak12** [comment]
Yes, I am using v1.2. This version fixed the issue for the usage of
<command type="..." />. However, the issue still exists when using
<commands assembly="..." />

**Comment by SzymonPobiega** [comment]
@adeepak12 ok. I missed that. Thanks for bringing that up!

**Comment by adeepak12** [comment]
@SzymonPobiega Thank you for looking into it.

**Comment by SzymonPobiega** [comment]
@adeepak12 #29 should solve this one.

**Comment by adeepak12** [comment]
Great! Thank you for fixing it.
